In [22]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
pd.set_option('display.precision',3)

In [28]:
df=pd.read_csv('aapl_data.csv',sep=',',skiprows=[1,2])
df.rename(columns={'Price':'Date'},inplace=True)
df.head()

         Date    Close     High      Low     Open     Volume
0  2021-03-25  117.454  118.496  115.905  116.431   98844700
1  2021-03-26  118.058  118.321  115.828  117.220   94071200
2  2021-03-29  118.233  119.392  117.591  118.487   80819200
3  2021-03-30  116.782  117.269  115.769  116.987   85671900
4  2021-03-31  118.974  120.308  118.000  118.487  118323800

In [29]:
df['prev_close']=df['Close'].shift(1)
df.head()

         Date    Close     High      Low     Open     Volume  prev_close
0  2021-03-25  117.454  118.496  115.905  116.431   98844700         NaN
1  2021-03-26  118.058  118.321  115.828  117.220   94071200     117.454
2  2021-03-29  118.233  119.392  117.591  118.487   80819200     118.058
3  2021-03-30  116.782  117.269  115.769  116.987   85671900     118.233
4  2021-03-31  118.974  120.308  118.000  118.487  118323800     116.782

In [30]:
df['returns']=(df['Close']-df['prev_close'])/df['prev_close']
df.head()

,Date,Close,High,Low,Open,Volume,prev_close,returns
0,2021-03-25,117.454,118.496,115.905,116.431,98844700,NaN,NaN
1,2021-03-26,118.058,118.321,115.828,117.220,94071200,117.454,0.005
2,2021-03-29,118.233,119.392,117.591,118.487,80819200,118.058,0.001
3,2021-03-30,116.782,117.269,115.769,116.987,85671900,118.233,-0.012
4,2021-03-31,118.974,120.308,118.000,118.487,118323800,116.782,0.019

In [ ]:
dfdf[df.isna().any(axis=1)]

,Date,Close,High,Low,Open,Volume,prev_close,returns
0,2021-03-25,117.454,118.496,115.905,116.431,98844700,NaN,NaN